### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by hakaserver** [cocktail-collective/cocktail#10]
Installation fails with the following error:

`Traceback (most recent call last):
  File "D:\Cocktail\venv\Lib\site-packages\cocktail\ui\startup\controller.py", line 155, in onZipDownloaded
    self.unzip_db_step.extract(reply, os.path.dirname(self.database_path))
  File "D:\Cocktail\venv\Lib\site-packages\cocktail\ui\startup\controller.py", line 66, in extract
    with zip_file.open(info) as file, open(
                                      ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USERNAME\\AppData\\Local\\cocktail\\cocktail\\Cache\\cocktail.sqlite3'
`

Tried both the latest .exe and manually in a venv with the same result.
Checked appdata\local\ but couldn't find any Cocktail folder.

**Comment by rfletchr** [comment]
hi @hakaserver thanks for reporting this

could you download this file 

`https://github.com/cocktail-collective/cocktail/releases/download/v0.1.0/database.zip`

and extract it to 

`C:\\Users\\USERNAME\\AppData\\Local\\cocktail\\cocktail\\Cache\\`

I'm getting a windows install setup so I can test this locally and fix it.

**Comment by rfletchr** [comment]
@hakaserver I've reproduced this and the issue should now be fixed.

please do a git pull and re-run cocktail

**Comment by hakaserver** [comment]
It is working now, thanks! 👍

**Comment by rfletchr** [comment]
thats great to hear. let me know how you get on.
